id: P97CF67A9
initial_creation_type: input
source_metadata:
  title: Gompa Tsultrim Nyingpo Series
  language: en
  description: 'Texts by and about Gompa Tsultrim Nyingpo (sgom pa tshul khrims snying
    po, 1116–1169), the eldest nephew of Gampopa:'
  volume:
    ea77d1110e5846f98affaefb433a4f21:
      title: A Brief Commentary on the Twelve Stanzas (Including the Divisions of
        the Stages of the Path for Individuals of the Three Capacities)
      parent: Lamrim
created_at: '2022-02-28T23:24:25.130654'
last_modified_at: '2022-02-28T23:24:25.130662'
